In [1]:
import numpy as np

##Datatypes and Attributes

Numpy's main type is ND Array...n dimensional array

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2=np.array([[1,2,3],
            [4,5,6.6],
            ])

In [7]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.6]])

In [20]:
a3=np.array([[[1,2],
             [4,5]],
             [[7,8],
             [10,11]]])

In [24]:
a2.shape

(2, 3)

In [26]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [27]:
import pandas as pd

In [29]:
df=pd.DataFrame(a2)

In [30]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.6

In [33]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [34]:
a2.size #Returns the number of elements.

6

In [35]:
#tutorial#336


It is a tedious task to enter the values in an array manually.Hence using functions.

In [36]:
ones=np.ones((2,2))

In [37]:
ones

array([[1., 1.],
       [1., 1.]])

In [38]:
zeros=np.zeros((2,2))

In [39]:
zeros

array([[0., 0.],
       [0., 0.]])

In [40]:
range_array=np.arange(0,10,1)

In [41]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
random_array=np.random.randint(1,15, size=(3,5))

In [46]:
random_array

array([[ 3, 11, 14,  4, 14],
       [ 7,  4,  5, 11,  3],
       [ 6, 11,  4, 11, 14]])

In [47]:
random_array_2=np.random.random((5,2))

In [48]:
random_array_2

array([[0.61290372, 0.24729034],
       [0.88044263, 0.94931867],
       [0.44355826, 0.17999273],
       [0.14968553, 0.16079213],
       [0.73873332, 0.58570101]])

In [49]:
random_array_2.shape

(5, 2)

Random Seed tutorial #337

In [59]:

random_array_4=np.random.randint(10, size=(5,3))
random_array_4

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [61]:
np.random.seed(0) 
random_array_4=np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Viewing Arrays and Matrices #338

In [62]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a1 , a2 , a3

(array([1, 2, 3]),
 array([[1. , 2. , 3. ],
        [4. , 5. , 6.6]]),
 array([[[ 1,  2],
         [ 4,  5]],
 
        [[ 7,  8],
         [10, 11]]]))

In [64]:
a1[0]

1

In [65]:
a3[0]

array([[1, 2],
       [4, 5]])

In [66]:
a3.shape

(2, 2, 2)

In [67]:
a2[1]

array([4. , 5. , 6.6])

In [70]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [71]:
comp=np.random.randint(10,size=(2,3,4,5))

In [72]:
comp

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [73]:
#Get the first 3 numbers of the innermost dimenstion

In [74]:
comp[:,:,:,:3]

array([[[[6, 7, 7],
         [5, 9, 8],
         [3, 0, 3],
         [2, 3, 8]],

        [[3, 3, 7],
         [9, 9, 0],
         [3, 2, 7],
         [0, 4, 5]],

        [[8, 4, 1],
         [8, 1, 1],
         [9, 3, 6],
         [0, 3, 5]]],


       [[[4, 6, 4],
         [4, 4, 8],
         [7, 5, 5],
         [5, 9, 3]],

        [[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0],
         [2, 9, 2]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0],
         [0, 6, 3]]]])

Manipulating and Comparing Arrays

In [75]:
##Arithmetic

In [76]:
a1

array([1, 2, 3])

In [77]:
ones=np.ones(3)

In [78]:
ones

array([1., 1., 1.])

In [79]:
a1+ones

array([2., 3., 4.])

In [80]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.6]])

In [81]:
a1*a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.8]])

In [82]:
a2*a3


ValueError: operands could not be broadcast together with shapes (2,3) (2,2,2) 

In [83]:
#The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations

In [84]:
#The smaler array is broadcasted across the larger array so they have compatibel shapes

#when operating with two arrays ,Numpy compares their shape element-wise. It starts with the trailing Dimensions. Two dimensions are compatible when they are equal or one of them is one 

In [85]:
#How to make a2 compatible with a3

In [86]:
a1/a2

array([[1.        , 1.        , 1.        ],
       [0.25      , 0.4       , 0.45454545]])

In [87]:
#Floor division removes the decimals
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [88]:
a2**a1

array([[  1.   ,   4.   ,  27.   ],
       [  4.   ,  25.   , 287.496]])

In [89]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 43.56]])

In [90]:
np.add(a1,a2)

array([[2. , 4. , 6. ],
       [5. , 7. , 9.6]])

In [91]:
np.mod(a1,a2)

array([[0., 0., 0.],
       [1., 2., 3.]])

In [92]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [93]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

Aggregation #340

Aggregation=Performing the same operation on a number of things

In [94]:
np.sum(a1)

6

#diff b/w sum() and np.sum()..Use Python methods on Python Datatypes and use Numpy's methods on numpy arrays

In [96]:
large_array=np.random.random(1000)
large_array

array([1.64940460e-01, 3.69808093e-01, 1.46441763e-01, 5.69618406e-01,
       7.03737279e-01, 2.88476437e-01, 4.33288062e-01, 7.56106694e-01,
       3.96098275e-01, 8.96038388e-01, 6.38921076e-01, 8.91554437e-01,
       6.80055569e-01, 4.49197738e-01, 9.78570928e-01, 1.16201910e-01,
       7.67023704e-01, 4.11820139e-01, 6.75439081e-01, 2.49796276e-01,
       3.13218332e-01, 9.65416221e-01, 5.88465085e-01, 6.59668412e-01,
       5.33206254e-01, 2.30533024e-01, 3.94869293e-01, 6.18808565e-01,
       4.74867515e-01, 4.70132189e-01, 7.16074531e-01, 2.87991004e-01,
       3.83462225e-01, 7.49169837e-01, 8.78452190e-01, 1.02863359e-01,
       9.23738895e-02, 3.54046662e-01, 5.51816259e-01, 3.36250935e-02,
       9.68961765e-01, 3.20997241e-01, 2.21262685e-01, 1.41263905e-01,
       9.72599271e-02, 9.84042241e-01, 2.60340928e-01, 5.37022521e-01,
       4.47926172e-01, 9.95690891e-02, 3.52311661e-01, 4.69249174e-01,
       8.41140130e-01, 9.04647744e-01, 3.75593838e-02, 5.08315449e-01,
      

In [97]:
%timeit sum(large_array)
%timeit np.sum(large_array)

517 µs ± 75.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
12.8 µs ± 1.94 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [98]:
np.mean(a2)

3.6

In [99]:
np.max(a2)

6.6

In [100]:
np.min(a2)

1.0

In [101]:
np.std(a2)

1.8618986725025255

In [102]:
np.var(a2)

3.4666666666666663

Std Deviation and Variance#341

In [104]:
#Measure of spread of Data

In [105]:
high_var_array=np.array([1,100,200,300,4000,5000,6000])
low_var_array=np.array([2,4,6,8,10])

In [106]:
np.var(high_var_array), np.var(low_var_array)

(6052832.775510205, 8.0)

In [107]:
np.std(high_var_array), np.std(low_var_array)

(2460.2505513687433, 2.8284271247461903)

In [109]:
np.mean(high_var_array), np.mean(low_var_array)#avg distance from the mean is std deviation

(2228.714285714286, 6.0)

Reshape and Transpose#342

In [110]:
#Lining up the inputs with the machine learing outputs

In [111]:
a2.shape

(2, 3)

In [112]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2,2) 

In [116]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [117]:
a2.shape

(2, 3)

In [122]:
a2_reshape=a2.reshape(2,3,1)

In [123]:
a2_reshape*a3

ValueError: operands could not be broadcast together with shapes (2,3,1) (2,2,2) 

In [126]:
a2.transpose().shape#Switches the axises

(3, 2)

Dot Product

In [132]:
np.random.seed(0)
mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10, size=(3,5))

mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7, 8, 1],
        [5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0]]))

In [133]:
np.dot(mat1,mat2)

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

In [135]:
mat1*mat2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [136]:
#For Dot Product, the shape should be correctly alligned....3*3.3*2=>3*2...It's just another tool in the arsenel to find patterns in the Machine learning process

In [137]:

#Dot Product Exercise for 

np.random.seed(0)
sales_amt=np.random.randint(20, size=(5,3))
sales_amt

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [138]:
weekly_sales=pd.DataFrame(sales_amt,
                         index=['Mon','Tue','Wed','Thurs','Fri'],
                         columns=['Almond Butter','Peanut butter', 'cashew butter'])

In [139]:
weekly_sales

Almond Butter  Peanut butter  cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [140]:
prices=np.array([10,8,12])

In [146]:
butter_prices=pd.DataFrame(prices.reshape(1,3),index=['price'],
                          columns=['Almond Butter','Peanut butter', 'cashew butter'])

In [147]:
butter_prices

Almond Butter  Peanut butter  cashew butter
price             10              8             12

In [148]:
butter_prices.shape

(1, 3)

In [149]:
weekly_sales.shape

(5, 3)

In [150]:
total_sales=prices.dot(sales_amt.T)

In [151]:
total_sales

array([240, 138, 458, 232, 142])

In [152]:
total_sales.sum()

1210

In [157]:
#Create Daily Sales

weekly_sales.shape, butter_prices.shape


((5, 3), (1, 3))

In [161]:
daily_sales=weekly_sales.dot(butter_prices.T)

In [162]:
daily_sales

price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [163]:
weekly_sales['Total($)']=daily_sales

In [164]:
weekly_sales

Almond Butter  Peanut butter  cashew butter  Total($)
Mon               12             15              0       240
Tue                3              3              7       138
Wed                9             19             18       458
Thurs              4              6             12       232
Fri                1              6              7       142